### ISSUE TITLE
which version of TF should it be?

### ISSUE THREAD

**Issue by xiaolongwu0713** [jgmakin/ecog2txt#2]
I installed tensorflow 1.5 by pip install tensorflow=1.15.2.
Then after I run below two line, I get tf 2.3, and give me some error about incompatible. 
git clone https://github.com/jgmakin/machine_learning.git
pip install -e machine_learning

Error message is blow:
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

tensorflow 2.3.0 requires gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.5.2 which is incompatible.
gym 0.14.0 requires cloudpickle~=1.2.0, but you'll have cloudpickle 1.3.0 which is incompatible.
kfac 0.2.2 requires tensorflow-probability==0.8, but you'll have tensorflow-probability 0.11.0 which is incompatible.
tensor2tensor 1.15.5 requires tensorflow-probability==0.7.0, but you'll have tensorflow-probability 0.11.0 which is incompatible.

**Comment by jgmakin** [comment]
There appears to be more than one issue.  For starters, I think you should begin by creating a new python environment: your error messages indicate that you have TF2.3 installed.  Try pip uninstalling it (or creating a new environment) and then

`pip install tensorflow==1.15`

or 

`pip install tensorflow-gpu==1.15`

**Comment by jgmakin** [comment]
Strike that: I think some changes in dependency requirements in other packages are now forcing TF2.x to be installed.  Hang on and I will try to work around them.

**Comment by xiaolongwu0713** [comment]
yes, I started with a virtual env actually, and also tried to uninstall tensorflow 2.3 then install 1.15.

**Comment by jgmakin** [comment]
It seems that the tensor2tensor library now tries to install newer versions of `gym` and `dopamine_rl`, which try to install TF2.x.  I have hard-coded the older (compatible) versions of these packages into the `setup.py` for `machine_learning`, which (I hope) fixes the problem.  Please try again in a fresh environment and let me know if you run into issues.

**Comment by xiaolongwu0713** [comment]
Yes, now I can install them without any issue. Thanks for you help.
